alternate: Web blog

# Assets
statics: / #//gcore.jsdelivr.net/gh/amehime/shoka@latest/

open_graph:
  #twitter_id:
  #google_plus:
  #fb_admins:
  #fb_app_id:

menu:
  home: / || home
  posts: / || feather
  archives: / || list-alt
  categories: / || th
  tags: / || tags
  friends: / || heart

Social Links
Usage: `Key: permalink || icon || color`
Key is the link label showing to end users.
Value before `||` delimiter is the target permalink,
secend value is the name of Font icon.
social:
  github: https://github.com/amehime || github || "#191717"
  google: https://plus.google.com/James-Kevin || google
  # twitter: https://twitter.com/amehime || twitter || "#00aff0"
  # zhihu: https://www.zhihu.com/people/rurismzk || zhihu || "#1e88e5"
  # music: https://music.163.com/#/user/home?id=12886823 || cloud-music || "#e60026"
  # weibo: https://weibo.com/amehime || weibo || "#ea716e"
  # about: https://about.me/amehime || address-card || "#3b5998"
  #email: mailto:yourname@mail.com || envelope || "#55acd5"
  #facebook: https://www.facebook.com/yourname || facebook
  #stackoverflow: https://stackoverflow.com/yourname || stack-overflow
  #youtube: https://youtube.com/yourname || youtube
  #instagram: https://instagram.com/yourname || instagram
  #skype: skype:yourname?call|chat || skype
  #douban: https://www.douban.com/people/yourname/ || douban
symbols_count_time:
  jsymbols: true
  time: true
  total_symbols: true
  total_time: true
  exclude_codeblock: false
  awl: 2
  wpm: 200
  suffix: "mins."
footer:
  # Specify the date when the site was setup. If not defined, current year will be used.
  since: 2022
  count: true

post:
  count: true


# ---------------------------------------------------------------
# Third Party Plugins & Services Settings
# ---------------------------------------------------------------

# Comments
# Valine
# For more information: https://valine.js.org, https://github.com/xCss/Valine
valine:
  appId: UTj70E2f04wg59oi4eBtXpJn-gzGzoHsz
  appKey: zWX0gPeLYV4mAS3S2fTUQHPy
  placeholder: åœ¨è¿™é‡Œè¸Šè·ƒå‘è¡¨å§ï¼âš¡æ³¨æ„å‹å¥½äº¤æµå“¦ğŸ’£ï¼Œæ–‡ç« æ•™ç¨‹ä¸­ç›¸å…³æŠ¥é”™å¯ğŸ“¸ï¼Œæ¬¢è¿äº¤æµå­¦ä¹ ğŸ’ª # Comment box placeholder
  avatar: retro # Gravatar style : mp, identicon, monsterid, wavatar, robohash, retro
  pageSize: 10 # Pagination size
  lang: zh-CN
  visitor: true # Article reading statistic
  NoRecordIP: false # Whether to record the commenter IP
  serverURLs: # When the custom domain name is enabled, fill it in here (it will be detected automatically by default, no need to fill in)
  tagMeta:
    visitor: æ–°æœ‹å‹
    master: ä¸»äºº
    friend: å°ä¼™ä¼´
    investor: é‡‘ä¸»ç²‘ç²‘
  tagColor:
    master: "var(--color-orange)"
    friend: "var(--color-aqua)"
    investor: "var(--color-pink)"
  tagMember:
    master:
      - 12c57913345e5c20107ae76a8d1cf703
      - 12C57913345E5C20107AE76A8D1CF703
      - 345E5C20107AE76A
      - 345e5c20107ae76a
      # - hash of master@email.com
      # - hash of master2@email.com
    friends:
      # - hash of friend@email.com
      # - hash of friend2@email.com
  powerMode: true

# bgm
audio:
   - title: åˆ—è¡¨1
      list:
        - https://music.163.com/#/playlist?id=2943811283
        - https://music.163.com/#/playlist?id=2297706586
   - title: åˆ—è¡¨2
      list:
        - https://music.163.com/#/playlist?id=2031842656

# Dependencies: https://github.com/amehime/hexo-renderer-multi-markdown-it
pangu: true

# ---------------------------------------------------------------
# analytics & SEO Settings
# ---------------------------------------------------------------
# ä»£ç å—é«˜äº®æ˜¾ç¤º
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ""
# Disable Baidu transformation on mobile devices.
disable_baidu_transformation: true

# Automatically add external URL with Base64 encrypt & decrypt.
exturl: true
